name: CI

on:
  push:
    branches: [ main ] 
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout release
      uses: actions/checkout@v3
        
    - name: Package install
      run: |
        ls -a
        yarn
        
    - name: Build
      run: |
        ls -a
        yarn build
        
        
    - name: Export
      run: |
        ls -a
        yarn export
        
    - name: archive drcloud 
      run: tar cvfz ./drcloud.tar.gz /build
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./drcloud.tar.gz s3://github-action-codedeploy-s3/archive/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name githubaction-test
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name githubaction-test-group
        --s3-location bucket=github-action-codedeploy-s3,bundleType=tgz,key=archive/drcloud.tar.gz
