name: CI

on:
  push:
    branches: [ main ] 
 
  # 이부분은 위의 trigger가 없어도 수동으로 동작 할 수 있게끔 해주는 역할을 합니다.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout release
      uses: actions/checkout@v3
        
    - name: Package install
      run: yarn
        
    - name: Build
      run: yarn build
        
    - name: Export
      run: |
        ls -a
        yarn export
       
    - name: zip distributions
      run: zip -r with-eat-build.zip ./build ./appspec.yml
       
    - name: AWS configure credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    - name: upload to S3
      run: aws s3 cp --region ap-northeast-2 ./with-eat-build.zip s3://with-eat-bucket/public/
      
    - name: deploy with AWS codeDeploy
      run: aws deploy create-deployment
        --application-name with-eat-deploy
        --deployment-config-name CodeDeployDefault.OneAtATime
        --deployment-group-name with-eat-deploy-group
        --s3-location bucket=with-eat-bucket,key=public/with-eat-build.zip,bundleType=zip
